package pr

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/gin-gonic/gin"

	"asika/common/config"
	"asika/common/db"
	"asika/common/llm"
	"asika/common/models"
)

var knownSummaryPrefixes = []string{
	"## AI Summary",
	"## Summary",
	"### AI-Generated Summary",
	"**AI Summary**",
	"🤖 Summary",
	"PR Summary",
}

var knownBotUsers = []string{
	"asika",
	"asika-bot",
	"opencode[bot]",
	"github-actions[bot]",
	"gitlab-bot",
}

type summaryResponse struct {
	Summary   string `json:"summary"`
	Generated bool   `json:"generated"`
	Source    string `json:"source"`
}

func getSummaryConfig() *models.AISummaryConfig {
	cfg := config.Current()
	if cfg == nil {
		return nil
	}
	return &cfg.AISummary
}

func isBotSummary(comment *models.PRComment, cfg *models.AISummaryConfig) bool {
	body := strings.TrimSpace(comment.Body)

	for _, prefix := range knownSummaryPrefixes {
		if strings.HasPrefix(body, prefix) {
			return true
		}
	}

	authorLower := strings.ToLower(comment.Author)
	botUsers := knownBotUsers
	if cfg != nil && len(cfg.BotUsers) > 0 {
		botUsers = cfg.BotUsers
	}
	for _, bot := range botUsers {
		if authorLower == strings.ToLower(bot) || strings.Contains(authorLower, strings.ToLower(bot)) {
			// Check if body looks like a summary (has markdown headers or bullet points)
			if len(body) > 50 && (strings.Contains(body, "#") || strings.Contains(body, "-") || strings.Contains(body, "1.")) {
				return true
			}
		}
	}

	return comment.IsBot && len(body) > 50
}

// SummarizePR returns the AI summary for a PR.
// It first checks if a bot already posted a summary in the comments.
// If none exists, optionally generates one using the configured LLM.
func SummarizePR(c *gin.Context) {
	user := c.GetString("username")
	repoGroupName := c.Param("repo_group")
	prID := c.Param("pr_id")

	cfgGlobal := config.Current()
	group := config.GetRepoGroupByName(cfgGlobal, repoGroupName)
	if group == nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "Repo group not found"})
		return
	}

	pr, err := dbGetPR(repoGroupName, prID)
	if err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "PR not found"})
		return
	}

	client := getClientForGroup(group, pr.Platform)
	if client == nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "No platform client available"})
		return
	}

	owner, repo := config.GetOwnerRepoFromGroup(group, pr.Platform)
	if owner == "" || repo == "" {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Cannot resolve repo"})
		return
	}

	ctx, cancel := context.WithTimeout(c.Request.Context(), 2*time.Minute)
	defer cancel()

	// Fetch existing comments
	comments, err := client.ListPRComments(ctx, owner, repo, pr.PRNumber)
	if err != nil {
		slog.Warn("failed to list PR comments", "error", err, "pr_id", prID)
		comments = nil
	}

	cfg := getSummaryConfig()

	// Check for existing bot summary
	if comments != nil {
		for _, comment := range comments {
			if isBotSummary(&comment, cfg) {
				c.JSON(http.StatusOK, summaryResponse{
					Summary:   comment.Body,
					Generated: false,
					Source:    comment.Author,
				})
				return
			}
		}
	}

	// No existing summary found; generate if enabled
	if cfg == nil || !cfg.Enabled || cfg.APIKey == "" {
		c.JSON(http.StatusOK, summaryResponse{
			Summary:   "",
			Generated: false,
			Source:    "",
		})
		return
	}

	// Generate summary from PR diff
	diffFiles, err := client.GetPRDiff(ctx, owner, repo, pr.PRNumber)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": fmt.Sprintf("Failed to get PR diff: %v", err)})
		return
	}

	commits, err := client.GetPRCommits(ctx, owner, repo, pr.PRNumber)
	if err != nil {
		commits = nil
	}

	body, err := client.GetPRBody(ctx, owner, repo, pr.PRNumber)
	if err != nil {
		body = ""
	}

	summary, err := generateSummary(cfg, pr, diffFiles, commits, body)
	if err != nil {
		slog.Error("failed to generate AI summary", "error", err, "pr_id", prID)
		c.JSON(http.StatusInternalServerError, gin.H{"error": fmt.Sprintf("Failed to generate summary: %v", err)})
		return
	}

	// Post as comment
	commentBody := fmt.Sprintf("## AI Summary\n\n%s\n\n---\n*Generated by asika AI*", summary)
	if err := client.CommentPR(ctx, owner, repo, pr.PRNumber, commentBody); err != nil {
		slog.Warn("failed to post AI summary as comment", "error", err, "pr_id", prID)
	}

	slog.Info("AI summary generated", "pr_id", prID, "user", user)

	c.JSON(http.StatusOK, summaryResponse{
		Summary:   commentBody,
		Generated: true,
		Source:    "asika",
	})
}

func generateSummary(cfg *models.AISummaryConfig, pr *models.PRRecord, diffFiles []models.DiffFile, commits []string, body string) (string, error) {
	baseURL := cfg.BaseURL
	if baseURL == "" {
		switch cfg.Provider {
		case "ollama":
			baseURL = "http://localhost:11434/v1"
		case "deepseek":
			baseURL = "https://api.deepseek.com/v1"
		default:
			baseURL = "https://api.openai.com/v1"
		}
	}
	model := cfg.Model
	if model == "" {
		switch cfg.Provider {
		case "ollama":
			model = "llama3"
		case "deepseek":
			model = "deepseek-chat"
		default:
			model = "gpt-4o-mini"
		}
	}

	llmClient := llm.NewClient(llm.Config{
		APIKey:  cfg.APIKey,
		BaseURL: baseURL,
		Model:   model,
	})

	maxLen := cfg.MaxDiffLength
	if maxLen <= 0 {
		maxLen = 8000
	}

	var diffParts []string
	totalLen := 0
	for _, df := range diffFiles {
		part := fmt.Sprintf("File: %s (%s, +%d/-%d)\n", df.Filename, df.Status, df.Additions, df.Deletions)
		if df.Patch != "" {
			patchLen := len(df.Patch)
			if patchLen > 500 {
				patchLen = 500
			}
			part += fmt.Sprintf("```diff\n%s\n```\n", df.Patch[:patchLen])
		}
		if totalLen+len(part) > maxLen {
			break
		}
		diffParts = append(diffParts, part)
		totalLen += len(part)
	}

	commitSummary := ""
	if len(commits) > 0 {
		commitSummary = "Commits:\n"
		for i, sha := range commits {
			if i >= 10 {
				commitSummary += fmt.Sprintf("... and %d more commits\n", len(commits)-10)
				break
			}
			commitSummary += fmt.Sprintf("- %s\n", sha)
		}
	}

	promptBody := ""
	if body != "" {
		if len(body) > 500 {
			promptBody = body[:500] + "..."
		} else {
			promptBody = body
		}
	}

	systemPrompt := `You are a code review assistant. Given a PR's diff, commit messages, and description, generate a concise PR summary covering:
1. What changed (key files and their purpose)
2. Why it changed (motivation from commits/description)
3. Potential risks or areas to focus on during review

Keep the summary under 300 words. Use markdown formatting.`
	if cfg.SystemPrompt != "" {
		systemPrompt = cfg.SystemPrompt
	}

	userTemplate := "## PR Title\n%s\n\n## Description\n%s\n\n## Files Changed\n%s\n\n%s"
	if cfg.UserPrompt != "" {
		userTemplate = cfg.UserPrompt
	}
	userPrompt := fmt.Sprintf(userTemplate, pr.Title, promptBody, strings.Join(diffParts, ""), commitSummary)

	result, err := llmClient.Chat(systemPrompt, userPrompt)
	if err != nil {
		return "", fmt.Errorf("llm summary: %w", err)
	}

	return result, nil
}

func dbGetPR(repoGroup, prID string) (*models.PRRecord, error) {
	var data []byte
	var err error

	prNumber, convErr := strconv.Atoi(prID)
	if convErr == nil {
		data, err = db.GetPRByIndex("", repoGroup, prNumber)
		if err == nil && data != nil {
			var pr models.PRRecord
			if json.Unmarshal(data, &pr) == nil && pr.RepoGroup == repoGroup {
				return &pr, nil
			}
		}
	}

	data, err = db.GetPRByIndex(prID, repoGroup, 0)
	if err != nil {
		return nil, err
	}
	if data == nil {
		return nil, fmt.Errorf("PR not found")
	}
	var pr models.PRRecord
	if err := json.Unmarshal(data, &pr); err != nil {
		return nil, err
	}
	return &pr, nil
}
