package db

// Bucket names
const (
	BucketConfig            = "config"
	BucketRepos             = "repos"
	BucketPRs               = "prs"
	BucketLogs              = "logs"
	BucketQueueItems        = "queue_items"
	BucketUsers             = "users"
	BucketSyncHistory       = "sync_history"
	BucketPRIndexByID       = "pr_index_by_id"
	BucketPRIndexByRG       = "pr_index_by_rg_num"
	BucketWebhookRetries    = "webhook_retries"
	BucketConfigHistory     = "config_history"
	BucketAPIKeys           = "api_keys"
	BucketSpamAuthors       = "spam_authors"
	BucketWebhookHealth     = "webhook_health"
	BucketReportHistory     = "report_history"
	BucketNotificationPrefs = "notification_prefs"
	BucketNotificationDedup = "notification_dedup"
	BucketTeamSpaces        = "team_spaces"
	BucketSpaceMembers      = "space_members"
	BucketSpaceSettings     = "space_settings"
	BucketIssuePRLinks      = "issue_pr_links"
	BucketIssuePRLinksByPR  = "issue_pr_links_by_pr"
	BucketPRDependencies    = "pr_dependencies"
	BucketPRDependents      = "pr_dependents"
	BucketPRTemplates       = "pr_templates"
	BucketSerialQueue       = "serial_queue"
	BucketCrossSpaceDeps    = "cross_space_deps"
	BucketEscalationRules   = "escalation_rules"
	BucketPRStacks          = "pr_stacks"
	BucketAuditLogIndex     = "audit_log_index"
	BucketWebhookDedup      = "webhook_dedup"
)
